// src/app/layout.js or app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by Next.js",
  openGraph: {
    title: "Create Next App",
    description: "Generated by Next.js",
    url: "https://main.d1ykkxg6efe5kj.amplifyapp.com/",  // Change this to your site URL
    siteName: "Next.js App",
    images: [
      {
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNDDaky4lvROb8utyqvD0en2KuVndJtZtjFQ&s",  // Replace with your social image URL
        width: 800,
        height: 600,
        alt: "Social Image Alt Text",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",  // Use summary_large_image for richer previews
    title: "Create Next App",
    description: "Generated by Next.js",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNDDaky4lvROb8utyqvD0en2KuVndJtZtjFQ&s",  // Replace with your social image URL
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Open Graph Meta Tags */}
        <meta property="og:title" content="Create Next App" />
        <meta property="og:description" content="Generated by Next.js" />
        <meta property="og:url" content="https://main.d1ykkxg6efe5kj.amplifyapp.com/" />
        <meta property="og:site_name" content="Next.js App" />
        <meta property="og:type" content="website" />
        <meta
          property="og:image"
          content="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNDDaky4lvROb8utyqvD0en2KuVndJtZtjFQ&s" // Replace with your social image URL
        />
        
        {/* Twitter Card Meta Tags */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Create Next App" />
        <meta name="twitter:description" content="Generated by Next.js" />
        <meta name="twitter:image" content="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNDDaky4lvROb8utyqvD0en2KuVndJtZtjFQ&s" />

        {/* Additional global meta tags or links */}
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
